### ISSUE TITLE
Not working in Arch?

### ISSUE THREAD

**Issue by Hebgbs** [zhuyaliang/user-admin#57] opened 2022-12-29 20:59 UTC
So I managed to install the AUR package, but I am unable to do stuff like automatic login for MATE when the same exact software works as expected in Ubuntu MATE.

How am I being dumb now, beyond expecting something for Ubuntu MATE to work for Arch?

**Comment by zhuyaliang** [comment] 2022-12-30 02:12
@Hebgbs 
What display manager do you use?
```
ls /etc/systemd/system/display-manager.service -l
```

**Comment by Hebgbs** [comment] 2022-12-30 03:59
> ls /etc/systemd/system/display-manager.service -l

`lrwxrwxrwx 1 root root 39 Dec 22 07:25 /etc/systemd/system/display-manager.service -> /usr/lib/systemd/system/lightdm.service`
Perhaps I should cross-examine this with Ubuntu MATE.

**Edit:** Same as in Ubuntu MATE. What else may it be? Because I cannot create users through this tool, let alone assign anyone to be automatically logged in.

**Comment by Hebgbs** [comment] 2022-12-30 21:47
If you want an easy in to Arch land, then EndeavourOS is pretty popular. Just set aside like, 32GiB for a test environment and have a play with it using the MATE desktop because that's what I have right now.

Not sure if you have any previous experience with Arch Linux, you might have made software used in an AUR package but I know not your current expertise with Arch.

**Comment by zhuyaliang** [comment] 2023-01-01 02:35
The ```accountsservice``` causes users using ```lightdm``` to fail to set automatic login,[accountsservice](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/issues/52).
Is there any prompt for user creation failure

**Comment by zhuyaliang** [comment] 2023-01-01 02:42
```
[mate@mouse ~]$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
What is your ```user-admin``` version

**Comment by Hebgbs** [comment] 2023-01-01 02:42
_Alright_ that's interesting. I tested this in my old broken copy of Manjaro MATE and it worked. At least, I can create the user.

_Damn it_ I now have to boot into EndeavourOS on my other laptop to reproduce my error.

**Comment by Hebgbs** [comment] 2023-01-01 02:59
Okay, so I confirmed the inability to create an account was some fluke. That or I am mixing up this with my experience in Ubuntu MATE which strictly disallows use of this application in live since no users exist.

But I can confirm even after making `/etc/gdm` with `sudo` I am unable to use automatic login which _does_ work in an installed instance of Ubuntu MATE.

**Comment by Hebgbs** [comment] 2023-01-01 03:35
Since you shared this information, I am using EndeavourOS _but_ without the theming changes so it shows as Arch:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
AUR build of `user-admin` is at 1.7.0-1.

**Comment by zhuyaliang** [comment] 2023-01-01 11:13
You can switch the display manager to ```gdm```

```
sudo pacman -S gdm
sudo systemctl disable lightdm
sudo systemctl enable gdm
reboot
```
This is my Display Manager
```
[mate@mouse ~]$ ls -l /etc/systemd/system/display-manager.service 
lrwxrwxrwx 1 root root 35 Jun 27  2021 /etc/systemd/system/display-manager.service -> /usr/lib/systemd/system/gdm.service
```

**Comment by zhuyaliang** [comment] 2023-01-03 11:05
@Hebgbs Whether the problem is solved after switching the display manager

**Comment by Hebgbs** [comment] 2023-01-04 23:50
Sorry for not replying sooner. This kind of got shoved to the bottom of my priorities even though I am constantly thinking about it.

So how does Ubuntu MATE do this? Can GDM somehow be made to load LightDM in its place so auto-login works? Because it works with GDM.

The only thing I can think of with how Ubuntu MATE does it is both are enabled but one is selected as default.

**Comment by zhuyaliang** [comment] 2023-01-05 01:24
I will switch to ```Ubuntu MATE``` to verify this problem

**Comment by Hebgbs** [comment] 2023-01-05 01:27
> I will switch to `Ubuntu MATE` to verify this problem

But see, Ubuntu MATE _isn't_ the problem. Ubuntu MATE works just fine. It uses LightDM, I sign in with LightDM, I edit user preferences in `mate-user-admin` and automatic login works just fine.

My issue with this software _built from the AUR_ is automatic login not working unless I install and use GDM. Which for someone wanting to evaluate MATE on Arch / EndeavourOS / other Arch derivative is kind of bananas.

**Comment by Hebgbs** [comment] 2023-01-05 01:31
Like, granted no sane person uses automatic login unless their dementia-addled grandparents just need the system to work with limited authentication prompts so I consider this a low-criticality issue so long user management works just fine, _which it does_ for an installed system using the MATE desktop. I've yet to test password assignment, which I should do some time soon.

**Comment by Hebgbs** [comment] 2023-01-09 01:37
Were you able to replicate my result?

**Comment by zhuyaliang** [comment] 2023-01-09 13:43
```Ubuntu Mate``` customized ```accountsservice``` and added support for automatic login of ```lightdm```
[0007-add-lightdm-support.patch](https://github.com/zhuyaliang/user-admin/files/10373612/0007-add-lightdm-support.patch)

**Comment by zhuyaliang** [comment] 2023-01-09 13:45
```
sudo apt source accountsservice
cd accountsservice-22.07.5/
cat debian/patches/0007-add-lightdm-support.patch
```

**Comment by zhuyaliang** [comment] 2023-01-09 13:50
```
sudo apt source accountsservice
cd accountsservice-22.07.5/
cat debian/patches/0007-add-lightdm-support.patch
```

**Comment by Hebgbs** [comment] 2023-01-11 23:01
Ahhh, so the Debian / Ubuntu build has LightDM support. I'm gonna need to dig through dependent packages and see if there is a toggle for it I need to rebuild with.

**Comment by zhuyaliang** [comment] 2023-01-12 01:18
I reopened this [issue](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/issues/52)，I will add PR to ```accountsservice``` to add the automatic login of ```lightdm```

**Comment by Hebgbs** [comment] 2023-01-12 02:39
Awesome. May this lead to some good news. I'll be watching for word from AUR package maintainer whenever there's an update to the build script.

**Comment by zhuyaliang** [comment] 2023-01-12 02:44
I'm not sure whether ```accountsservice``` will accept my suggestion and PR

**Comment by Hebgbs** [comment] 2023-01-12 02:57
Even if they don't, couldn't you just fork it and create a variant of `accountservices` optimized for MATE called `mate-accountservices` or something to that effect? It'd be more work, surely but it'd be a sure-fire way of dealing with it.

**Comment by zhuyaliang** [comment] 2023-01-12 03:13
I will try to persuade them

**Comment by Hebgbs** [comment] 2023-01-29 20:48
_Actually_ I have another idea; what would stop you from making an AUR package that just downloads Canonical's implementation of Account Services and use it in lieu of _actual_ account services? Wouldn't there be some way to tell Pacman the dependency is satisfied without having to rebuild everything around it, since the files will be in the same place?

If you end up needing to do something drastic like host your own repository so packages from _that_ repo can be installed in place of _official_ account services, that would be an acceptable alternative wouldn't it?

**Edit:** On second thought, could you just provide a modified PKGBUILD file so that it builds _as_ `accountservices` and be installed? I wouldn't mind dropping into a TTY and making that magic happen for sake of testing.

**Comment by zhuyaliang** [comment] 2023-01-30 04:20
@Hebgbs I have submitted the code to [```accountsservice``` ](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/115),

**Comment by zhuyaliang** [comment] 2023-02-08 08:41
@Hebgbs ```accountsservice``` is ready to merge support for ```lightdm``` automatic login,I will take time this week to test the code submitted to ```accountsservice``` on different systems,If the test is successful, the code will be merged

**Comment by zhuyaliang** [comment] 2023-02-24 02:19
@Hebgbs [accountsservice](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/commit/68e8a5d3d57344e893becdd80a4ead48438717e8) already supports automatic login of ```lightdm```,Can I close this issue

**Closed as completed** 2023-07-13 08:37 UTC
